server:
  port: 8081

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    timeout: 5000

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user?characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: root